server {
    listen       80;
    server_name  localhost;

    # 静态网页资源根目录
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 支持 Vue/Vite 路由刷新防 404
        try_files $uri $uri/ /index.html;
    }

    # 错误页面重定向
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
